### ISSUE TITLE
请问目前棋力如何，能下过弈心吗？

### ISSUE THREAD

**Issue by 782832949** [anxingle/AlphaPig#2]

**Comment by anxingle** [comment]
调高n_playout大于1000，可以。还在训练中。尝试其他的网络和对进程对弈来提高棋力。

**Comment by anxingle** [comment]
已经增加了 快速入门启动脚本，可在docker环境下快速启动。

**Comment by joezou** [comment]
我下载5000多盘人类对局，预处理之后，进行监督训练，但是loss一直下降不了，这是什么原因？

<img width="1057" alt="Image" src="https://github.com/user-attachments/assets/ffd8e9cb-d989-4a41-bb0a-b5a2eb888bf9" />
