### ISSUE TITLE
同学你还在所里吗，能不能线下交流一下？

### ISSUE THREAD

**Issue by initial-h** [anxingle/AlphaPig#4]
可以加个微信交流一下吗，我在做这个的过程中遇到了一些问题想请教一下，非常感谢。我的邮箱hongming.zhang@ia.ac.cn

**Comment by anxingle** [comment]
你好，已经工作了，不在所里了。这个月不在北京，估计要下个月回京津。

**Comment by initial-h** [comment]
可以加个微信吗，发送到邮箱我加一下，感谢。

**Comment by anxingle** [comment]
已发，请查收邮件。
